call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'itchyny/lightline.vim'
Plug 'justinmk/vim-dirvish'

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-fugitive'

Plug 'junegunn/fzf', {'dir': '$HOME/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'

Plug 'scrooloose/nerdcommenter'

Plug 'jiangmiao/auto-pairs'

Plug 'sheerun/vim-polyglot'
call plug#end()

set hidden

" Config tab/space handling
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Config search
set ignorecase
set smartcase
set gdefault
set hlsearch  " Highlight all matches
set incsearch

set pastetoggle=<F2>

set nobackup noswapfile
set undofile undodir=/tmp/nvim/undodir

set autoread

set noshowmode

set number
set cursorline

set background=dark
colorscheme gruvbox

function! <SID>StripTrailingWhitespaces()
    let _s=@/
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    let @/=_s
    call cursor(l, c)
endfunction

autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

let g:mapleader = ' '

" For autocompletion with <Tab>
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Buffer movements
nmap <leader>l :bnext<cr>
nmap <leader>h :bprev<cr>
nmap <leader>d :bdelete<cr>

" Disable arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" add shortcut for <esc>
imap jj <esc>

" " insert a new line without going in insert mode
nmap <cr> o<esc>

" " Change background color to easily work on dark/light places.
map <Leader>bg :let &background = ( &background == "dark"? "light" : "dark" )<CR>

" move line by line visually
nmap j gj
nmap k gk

" select the last pasted text
nnoremap gp `[v`]

" fzf.vim
nnoremap ; :Buffers<cr>
nnoremap <leader>f :Files<cr>
nnoremap <leader>r :Rg<cr>

" lightline.vim
let g:lightline = {
\     'colorscheme': 'wombat',
\     'active': {
\         'left': [['mode', 'paste'], ['gitbranch', 'readonly', 'filename', 'modified']],
\         'right': [['lineinfo'], ['percent'],
\             ['fileformat', 'fileencoding', 'filetype']
\         ],
\     },
\     'component_function': {
\         'gitbranch': 'fugitive#head'
\     }
\ }
