- name: install cli programs
  xbps:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - fzf
    - autojump
    - curl
    - wget
    - gzip
    - ripgrep
    - tig
    - tmux
    - cloc
    - tree
    - htop
    - unzip
