# TODO: cquery for LSP
---
- name: Install clang
  apt:
    name: clang

- name: Install clang tooling
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - clang-format
    - clang-tidy
    - clang-tools

- name: Install gcc
  apt:
    name: gcc

- name: Install build tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - autoconf
    - cmake
    - make
    - meson
    - automake

- name: Install C/C++ debugging tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gdb
    - valgrind
